[package]
name = "kokoro-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kokoro"
path = "src/main.rs"

[[bin]]
name = "hello"
path = "src/hello.rs"

[dependencies]
anyhow = "1.0.95"
hound = "3.5.1"
ndarray = "0.16.1"
ort = "=2.0.0-rc.9"
